### ISSUE TITLE
prelaunchr-laravel  -- questions

### ISSUE THREAD

**Issue by numinds** [jonstavis/prelaunchr-laravel#3]
Hi Jon,

You don't know me, we've never talked. I'm looking into the prelaunchr kinds of apps, as I need/want to have my own "Viral" growth kind of app. I'd like to talk to you about the status of this app, and if you might be up to making some changes on a freelance basis.

At the same time can you tell me if the app is actually in a state to work if ported to a VM with the requisite php/db/supporting apps on the VM? 

I've got a test VM -- centos8/apache with the usual support apps.

thanks

-bruce

**Comment by jonstavis** [comment]
Hi Bruce,  great to hear from you.  Could you email me to discuss further?

**Comment by numinds** [comment]
Hi Jon.

Thanks for the reply. Gotta love the 'net!

I'm doing a small project to test out if my target users are interested in a service I want to offer. To really test this out I need/want to hae a referral/viral app that's connected to a network/community.

The idea is for the "user" to visit the site see what the project is about, and then decide to join the community. At the smae time, I want to provide some type of "reward" process to encourage the user to go forth and evangelize/market to other users.

I'm looking at a few apps that have riffed off of the old prelancher app and saw your app. The community/network function will probably come from modifying drupal+communityApp.

At this point, I'm looking to quickly test the prelaunchr app, and if it looks reasonable (and I can modify it), then I'll go from there. 

Ideally, the app looks reasonable and I can mod it for my needs, and be able to merg it into the drupal+community app I'm thinking about.

thanks

-bruce
usc_dog@gmail.com

 

     On Thursday, June 18, 2020, 10:08:28 AM EDT, jonstavis <notifications@github.com> wrote:  
 
 


Hi Bruce, great to hear from you. Could you email me to discuss further? jstavis@gmail.com

**Comment by jonstavis** [comment]
Sounds good!  Keep in mind that this project is 5 years old and I haven't touched it in ages, so it may need considerable work to get it to run on the most recent version of Laravel.  Feel free to fork it or submit a pull request to this project.

If you find yourself having any questions or think you want some custom work done on it let me know.

**Comment by numinds** [comment]
Hi Jon.

Thanks.

I'm setting up a test laravel system with apache.

As I understand some things, it appears /var/www/html/laravel should be the dir for laravel and should be docroot. Do you have a test apache conf file for laravel with a test app? I'm looking to have something I can inspect to mae sure I dont screw something up out of the box.

-bruce
usc_dog@gmail.com




     On Thursday, June 18, 2020, 04:52:44 PM EDT, jonstavis <notifications@github.com> wrote:  
 
 


Sounds good! Keep in mind that this project is 5 years old and I haven't touched it in ages, so it may need considerable work to get it to run on the most recent version of Laravel. Feel free to fork it or submit a pull request to this project.

If you find yourself having any questions or think you want some custom work done on it let me know.

**Comment by numinds** [comment]
Hi Jon

Thanks for your reply. 

I've been testing how to setup centos/apache/laravel. Finally got this part to work.

I'm looking over the 
 https://github.com/jonstavis/prelaunchr-laravel

repos to try to understand/figure out how to get the project installed n my VM.

Do I have to use git, to clone the repo first??

Or can I invoke Composer to have ti get the repo?

composer create-project jonstavis/prelaunchr-laravel:dev-master prelaunchr 

results in::
>>Creating a "jonstavis/prelaunchr-laravel" project at "./prelaunchr"
 
 [InvalidArgumentException] 
 Could not find package jonstavis/prelaunchr-laravel . 
 
 
Thoughts/Comments??

thanks
-bruce



     On Thursday, June 18, 2020, 04:52:44 PM EDT, jonstavis <notifications@github.com> wrote:  
 
 


Sounds good! Keep in mind that this project is 5 years old and I haven't touched it in ages, so it may need considerable work to get it to run on the most recent version of Laravel. Feel free to fork it or submit a pull request to this project.

If you find yourself having any questions or think you want some custom work done on it let me know.

**Comment by numinds** [comment]
Morning Jon.

I've been trying to update the old prelaunchr app. I'm now at a point where I've gone through the "readme.md" file. I'm now firing up the php artisan:serve to try to launch the app, see what it can do/look like.

If you're interested, it might be a good time to discuss with you how much it would cost to get this app up/running.

I'm using:
Centos 8
laravel 7
php 7
mysql
etc..

I've already got a test digitalocean VM -- 3G, centos 8

Let me now your thoughts on this!

thanks

-bruce
usc_dog@yahoo.com



     On Friday, June 19, 2020, 06:53:14 AM EDT, m d <usc_dog@yahoo.com> wrote:  
 
  

Hi Jon.

Thanks.

I'm setting up a test laravel system with apache.

As I understand some things, it appears /var/www/html/laravel should be the dir for laravel and should be docroot. Do you have a test apache conf file for laravel with a test app? I'm looking to have something I can inspect to mae sure I dont screw something up out of the box.

-bruce
usc_dog@gmail.com




     On Thursday, June 18, 2020, 04:52:44 PM EDT, jonstavis <notifications@github.com> wrote:  
 
 


Sounds good! Keep in mind that this project is 5 years old and I haven't touched it in ages, so it may need considerable work to get it to run on the most recent version of Laravel. Feel free to fork it or submit a pull request to this project.

If you find yourself having any questions or think you want some custom work done on it let me know.

**Comment by jonstavis** [comment]
Hi Bruce, can you email me?  jstavis@gmail.com

The email you provided bounced for me

**Comment by numinds** [comment]
Hi Jon,
Thanks for replying to me. 

Im making progress on the app! However, regarding the "Admin" stuff, I have no clue. But still researching it.
If you have a min, and it's not too much, could you tell me what functionality the admin side was supposed to do?
It appears that the Laravel 7 process is quite different and Routes/Controller/methods logic need to be redone. It might help if I had an inkling into what the stuff was supposed to do.
Also, is the Admin function in the 3rd party package, or does it also interface to the prelaunchr app?
thanks
-bruceusc_dog@yahoo.com

    On Monday, July 13, 2020, 3:09:40 PM EDT, jonstavis <notifications@github.com> wrote:  
 
 


Closed #3.

**Comment by arielbsd** [comment]
@numinds where you able to put this app to work?
